# Generated by Django 5.0.6 on 2025-09-24 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_city_event_country_event_season_event_state'),
        ('locations', '0002_season_league_season_season_type_season_teams_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='short_description',
        ),
        migrations.AddField(
            model_name='event',
            name='allow_withdrawals',
            field=models.BooleanField(default=True, verbose_name='Allow Withdrawals'),
        ),
        migrations.AddField(
            model_name='event',
            name='entry_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Entry Deadline'),
        ),
        migrations.AddField(
            model_name='event',
            name='freeze_rosters',
            field=models.BooleanField(default=False, verbose_name='Freeze Rosters'),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, choices=[('north', 'North Region'), ('south', 'South Region'), ('east', 'East Region'), ('west', 'West Region'), ('central', 'Central Region')], max_length=20, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='event',
            name='rule_set',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Rules'), ('modified', 'Modified Rules'), ('custom', 'Custom Rules')], max_length=20, verbose_name='Rule Set'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_name',
            field=models.CharField(blank=True, help_text='If provided, the short name will be used in event notifications sent via SMS', max_length=100, verbose_name='Event Short Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='stature',
            field=models.CharField(choices=[('single_points', 'Single Points Event'), ('double_points', 'Double Points Event'), ('championship', 'Championship Event'), ('exhibition', 'Exhibition Event')], default='single_points', max_length=20, verbose_name='Stature'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.season', verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Event Name'),
        ),
    ]
