# Generated by Django 5.0.6 on 2025-09-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accept_deposits',
            field=models.BooleanField(default=False, verbose_name='Accept Deposits'),
        ),
        migrations.AddField(
            model_name='event',
            name='accept_schedule_requests',
            field=models.BooleanField(default=False, verbose_name='Accept Schedule Requests'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_online_pay',
            field=models.BooleanField(default=False, verbose_name='Allow Online Pay'),
        ),
        migrations.AddField(
            model_name='event',
            name='default_deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Default Deposit Amount'),
        ),
        migrations.AddField(
            model_name='event',
            name='default_entry_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Default Entry Fee'),
        ),
        migrations.AddField(
            model_name='event',
            name='gate_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gate Fee Amount'),
        ),
        migrations.AddField(
            model_name='event',
            name='gate_fee_type',
            field=models.CharField(blank=True, choices=[('per_person', 'Per Person'), ('per_car', 'Per Car'), ('per_day', 'Per Day'), ('flat_fee', 'Flat Fee')], max_length=20, null=True, verbose_name='Gate Fee Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_gate_fee',
            field=models.BooleanField(default=False, verbose_name='Has Gate Fee'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Deadline'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_reminder_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Reminder Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='roster_freeze_date',
            field=models.DateField(blank=True, null=True, verbose_name='Roster Freeze Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_request_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Schedule Request Deadline'),
        ),
        migrations.AddField(
            model_name='event',
            name='send_payment_reminders',
            field=models.BooleanField(default=False, verbose_name='Send Payment Reminders'),
        ),
        migrations.AddField(
            model_name='event',
            name='withdraw_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Withdraw Deadline'),
        ),
    ]
