# Generated by Django 5.0.6 on 2025-09-24 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_accept_deposits_event_accept_schedule_requests_and_more'),
        ('locations', '0003_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rule_set',
        ),
        migrations.AddField(
            model_name='event',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.rule', verbose_name='Rule Set'),
        ),
    ]
