# Generated by Django 5.0.6 on 2025-09-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_rule_set_event_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allow_withdrawals',
            field=models.BooleanField(default=False, verbose_name='Allow Withdrawals'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
