# Generated by Django 5.0.6 on 2025-09-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_allow_withdrawals_alter_event_is_public'),
        ('locations', '0006_alter_site_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='Selecciona los sitios donde se realizará este evento', related_name='events', to='locations.site', verbose_name='Sites'),
        ),
    ]
