# Generated by Django 5.0.6 on 2025-09-24 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_sites'),
        ('locations', '0006_alter_site_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sites',
        ),
        migrations.AddField(
            model_name='event',
            name='additional_sites',
            field=models.ManyToManyField(blank=True, help_text='Sitios adicionales donde se realizará el evento', related_name='additional_events', to='locations.site', verbose_name='Additional Sites'),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_site',
            field=models.ForeignKey(blank=True, help_text='Sitio principal donde se realizará el evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_events', to='locations.site', verbose_name='Primary Site'),
        ),
    ]
