# Generated by Django 4.2.24 on 2025-10-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_sites_event_additional_sites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la División')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('age_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Mínima')),
                ('age_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Máxima')),
                ('skill_level', models.CharField(blank=True, help_text='Ej: Principiante, Intermedio, Avanzado', max_length=50, verbose_name='Nivel de Habilidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'División',
                'verbose_name_plural': 'Divisiones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.division', verbose_name='División'),
        ),
    ]
