# Generated by Django 4.1 on 2025-12-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_fix_date_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del Tipo"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0d2c54",
                        help_text="Color en formato hexadecimal",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-calendar",
                        help_text="Clase de icono Font Awesome",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Evento",
                "verbose_name_plural": "Tipos de Eventos",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de evento (Liga, Showcase, Torneo, World Series, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventtype",
                verbose_name="Tipo de Evento",
            ),
        ),
    ]
