# Generated by Django 4.1 on 2025-12-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventtype_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stripe_payment_profile',
            field=models.CharField(blank=True, help_text='ID del perfil de pago de Stripe para este evento', max_length=255, null=True, verbose_name='Perfil de Pago Stripe'),
        ),
    ]
