# Generated by Django 4.1 on 2025-12-03 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_stripe_payment_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tarifa de Entrada',
                'verbose_name_plural': 'Tipos de Tarifas de Entrada',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='gate_fee_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de tarifa de entrada (Player Gate Fee, Spectator Gate Fee, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.gatefeetype', verbose_name='Tipo de Tarifa de Entrada'),
        ),
    ]
