# Generated by Django 4.1 on 2025-12-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_gatefeetype_alter_event_gate_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio del período de registro', null=True, verbose_name='Entry Start Date'),
        ),
    ]
