# Generated by Django 4.1 on 2025-12-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_entry_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_player_list',
            field=models.BooleanField(default=False, help_text='Mostrar lista de jugadores en el evento', verbose_name='Display Player List'),
        ),
    ]
