# Generated by Django 4.1 on 2025-12-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_hotel_capacity'),
        ('events', '0015_event_display_player_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel sede donde se alojarán los participantes del evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.hotel', verbose_name='Hotel Sede'),
        ),
    ]
