# Generated by Django 4.1 on 2025-12-04 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_hotel_capacity'),
        ('events', '0016_event_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_hotels',
            field=models.ManyToManyField(blank=True, help_text='Hoteles adicionales donde se alojarán los participantes del evento', related_name='additional_events', to='locations.hotel', verbose_name='Hoteles Adicionales'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel sede principal donde se alojarán los participantes del evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_events', to='locations.hotel', verbose_name='Hotel Sede'),
        ),
    ]
