# Generated by Django 4.1 on 2025-12-04 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_hotel_contact_email_hotel_contact_name_and_more'),
        ('events', '0017_event_additional_hotels_alter_event_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo de la persona de contacto', max_length=200, verbose_name='Nombre')),
                ('photo', models.ImageField(blank=True, help_text='Foto de la persona de contacto', null=True, upload_to='event_contacts/', verbose_name='Foto')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico de contacto', max_length=254, verbose_name='Email')),
                ('information', models.TextField(blank=True, help_text='Información adicional sobre el contacto', verbose_name='Información')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('city', models.ForeignKey(blank=True, help_text='Ciudad de la persona de contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_contacts', to='locations.city', verbose_name='Ciudad')),
                ('country', models.ForeignKey(blank=True, help_text='País de la persona de contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_contacts', to='locations.country', verbose_name='País')),
                ('state', models.ForeignKey(blank=True, help_text='Estado de la persona de contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_contacts', to='locations.state', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Contacto de Evento',
                'verbose_name_plural': 'Contactos de Eventos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_contact',
            field=models.ForeignKey(blank=True, help_text='Persona de contacto para el evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcontact', verbose_name='Contacto del Evento'),
        ),
    ]
