# Generated by Django 4.1 on 2025-12-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_eventcontact_event_event_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_welcome_body',
            field=models.TextField(blank=True, help_text='Contenido HTML del correo de bienvenida que se enviará a los participantes', null=True, verbose_name='Cuerpo del Correo de Bienvenida (HTML)'),
        ),
    ]
