# Generated by Django 4.1 on 2025-12-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_change_division_to_manytomany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='additional_hotels',
        ),
        migrations.RemoveField(
            model_name='event',
            name='display_player_list',
        ),
        migrations.RemoveField(
            model_name='event',
            name='email_welcome_body',
        ),
        migrations.RemoveField(
            model_name='event',
            name='entry_start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_contact',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stripe_payment_profile',
        ),
        migrations.DeleteModel(
            name='EventContact',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
