# Generated by Django - Add position and organization fields to EventContact

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_change_event_contact_to_manytomany'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcontact',
            name='position',
            field=models.CharField(
                blank=True,
                help_text='Cargo o posición (ej: Director Ejecutivo, Coordinador, Manager)',
                max_length=200,
                verbose_name='Cargo'
            ),
        ),
        migrations.AddField(
            model_name='eventcontact',
            name='organization',
            field=models.CharField(
                blank=True,
                help_text='Organización o empresa a la que pertenece',
                max_length=200,
                verbose_name='Organización'
            ),
        ),
        migrations.AlterModelOptions(
            name='eventcontact',
            options={
                'ordering': ['name'],
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos'
            },
        ),
    ]



