# Generated by Django 4.1 on 2025-12-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.URLField(blank=True, help_text='URL del banner del evento desde el sistema multimedia', null=True, verbose_name='Banner del Evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.URLField(blank=True, help_text='URL del logo del evento desde el sistema multimedia', null=True, verbose_name='Logo del Evento'),
        ),
    ]
