# Generated by Django 6.0 on 2026-01-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_add_banner_and_logo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='service_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Service fee percentage to be added to the checkout total', max_digits=5, null=True, verbose_name='Service Fee (%)'),
        ),
    ]
