# Generated by Django 6.0 on 2026-01-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_event_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_spectator',
            field=models.TextField(blank=True, help_text='Descripción del evento para Spectators', verbose_name='Description (Spectator)'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_team_manager',
            field=models.TextField(blank=True, help_text='Descripción del evento para Team Managers', verbose_name='Description (Team Manager)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_spectator',
            field=models.CharField(blank=True, help_text='Nombre del evento para Spectators', max_length=200, verbose_name='Event Name (Spectator)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_team_manager',
            field=models.CharField(blank=True, help_text='Nombre del evento para Team Managers', max_length=200, verbose_name='Event Name (Team Manager)'),
        ),
    ]
