# Generated by Django 6.0 on 2026-01-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_add_user_type_specific_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='default_entry_fee_spectator',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Default Entry Fee (Spectator)'),
        ),
        migrations.AddField(
            model_name='event',
            name='default_entry_fee_team_manager',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Default Entry Fee (Team Manager)'),
        ),
        migrations.AddField(
            model_name='event',
            name='gate_fee_amount_spectator',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gate Fee Amount (Spectator)'),
        ),
        migrations.AddField(
            model_name='event',
            name='gate_fee_amount_team_manager',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gate Fee Amount (Team Manager)'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_deadline_spectator',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Deadline (Spectator)'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_deadline_team_manager',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Deadline (Team Manager)'),
        ),
        migrations.AddField(
            model_name='event',
            name='service_fee_spectator',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Service Fee (%) (Spectator)'),
        ),
        migrations.AddField(
            model_name='event',
            name='service_fee_team_manager',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Service Fee (%) (Team Manager)'),
        ),
    ]
