# Generated by Django 6.0 on 2026-01-10 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_add_user_type_specific_pricing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gate_fee_type_spectator',
            field=models.ForeignKey(blank=True, help_text='Tipo de tarifa de entrada para Spectator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_spectator', to='events.gatefeetype', verbose_name='Tipo de Tarifa de Entrada (Spectator)'),
        ),
        migrations.AddField(
            model_name='event',
            name='gate_fee_type_team_manager',
            field=models.ForeignKey(blank=True, help_text='Tipo de tarifa de entrada para Team Manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_team_manager', to='events.gatefeetype', verbose_name='Tipo de Tarifa de Entrada (Team Manager)'),
        ),
    ]
