# Generated by Django 6.0 on 2026-01-10 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_event_gate_fee_type_spectator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Fecha del día del itinerario', verbose_name='Día')),
                ('day_number', models.PositiveIntegerField(help_text='Número del día en el evento (Día 1, Día 2, etc.)', verbose_name='Número de Día')),
                ('title', models.CharField(help_text="Título o nombre del día (ej: 'Día de Apertura', 'Día de Competencia', etc.)", max_length=200, verbose_name='Título del Día')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de las actividades del día', verbose_name='Descripción')),
                ('schedule_items', models.JSONField(blank=True, default=list, help_text='Lista de actividades con hora y descripción (formato JSON)', verbose_name='Actividades del Día')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Item de Itinerario',
                'verbose_name_plural': 'Items de Itinerario',
                'ordering': ['day', 'day_number'],
                'indexes': [models.Index(fields=['event', 'day'], name='events_even_event_i_ba1827_idx')],
                'unique_together': {('event', 'day')},
            },
        ),
    ]
