# Generated by Django 6.0 on 2026-01-10 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_eventitinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Nombre del servicio adicional', max_length=200, verbose_name='Nombre del Servicio')),
                ('service_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Almuerzo'), ('dinner', 'Cena'), ('parking', 'Estacionamiento'), ('wifi', 'WiFi'), ('laundry', 'Lavandería'), ('airport_shuttle', 'Transporte al Aeropuerto'), ('gym', 'Gimnasio'), ('pool', 'Piscina'), ('spa', 'Spa'), ('transportation', 'Transporte'), ('meal_plan', 'Plan de Comidas'), ('equipment_rental', 'Alquiler de Equipo'), ('tournament_fee', 'Tarifa de Torneo'), ('registration_packet', 'Paquete de Registro'), ('merchandise', 'Mercancía'), ('other', 'Otro')], default='other', max_length=30, verbose_name='Tipo de Servicio')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del servicio', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del servicio', max_digits=10, verbose_name='Precio')),
                ('is_per_person', models.BooleanField(default=False, help_text='Indica si el precio es por persona o por servicio', verbose_name='Por Persona')),
                ('is_per_night', models.BooleanField(default=False, help_text='Indica si el precio es por noche (útil para servicios de hotel)', verbose_name='Por Noche')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el servicio está disponible para este evento', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('event', models.ForeignKey(help_text='Evento al que pertenece este servicio adicional', on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Servicio Adicional del Evento',
                'verbose_name_plural': 'Servicios Adicionales del Evento',
                'ordering': ['event', 'order', 'service_name'],
            },
        ),
    ]
