# Generated by Django 6.0 on 2026-01-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_add_event_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventitinerary',
            options={'ordering': ['user_type', 'day', 'day_number'], 'verbose_name': 'Item de Itinerario', 'verbose_name_plural': 'Items de Itinerario'},
        ),
        migrations.RemoveIndex(
            model_name='eventitinerary',
            name='events_even_event_i_ba1827_idx',
        ),
        migrations.AlterUniqueTogether(
            name='eventitinerary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventitinerary',
            name='user_type',
            field=models.CharField(choices=[('player', 'Jugador'), ('team_manager', 'Team Manager'), ('spectator', 'Spectator')], default='player', help_text='Tipo de usuario para el que es este itinerario', max_length=20, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='eventitinerary',
            unique_together={('event', 'user_type', 'day')},
        ),
        migrations.AddIndex(
            model_name='eventitinerary',
            index=models.Index(fields=['event', 'user_type', 'day'], name='events_even_event_i_42c5dd_idx'),
        ),
    ]
