# Generated by Django 6.0 on 2026-01-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_add_user_type_to_event_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_player',
            field=models.TextField(blank=True, help_text='Descripción del evento para Individual Players', verbose_name='Description (Individual Player)'),
        ),
    ]
