# Generated by Django 6.0 on 2026-01-10 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_add_description_player_to_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIncludes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('player', 'Jugador'), ('team_manager', 'Team Manager'), ('spectator', 'Spectator')], default='player', help_text='Tipo de usuario para el que es este item incluido', max_length=20, verbose_name='Tipo de Usuario')),
                ('title', models.CharField(help_text="Título del item incluido (ej: 'Comida incluida', 'Transporte incluido', etc.)", max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del item incluido (opcional)', verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si este item está activo y se mostrará', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes_items', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Item Incluido',
                'verbose_name_plural': 'Items Incluidos',
                'ordering': ['user_type', 'order', 'title'],
                'indexes': [models.Index(fields=['event', 'user_type', 'order'], name='events_even_event_i_2fd110_idx')],
                'unique_together': {('event', 'user_type', 'title')},
            },
        ),
    ]
