# Generated by Django 6.0 on 2026-01-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_add_event_includes_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_mobile',
            field=models.URLField(blank=True, help_text='URL del banner móvil del evento desde el sistema multimedia', null=True, verbose_name='Banner Móvil del Evento'),
        ),
    ]
