# Generated by Django 6.0 on 2026-01-13 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_add_banner_mobile_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Visitas'),
        ),
        migrations.CreateModel(
            name='EventView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_views', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita de Evento',
                'verbose_name_plural': 'Visitas de Eventos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'ip_address'], name='events_even_event_i_b8c2e1_idx'), models.Index(fields=['event', 'session_key'], name='events_even_event_i_dd4f28_idx')],
            },
        ),
    ]
