# Generated by Django 6.0 on 2026-01-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_event_views_eventview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL of the event video (YouTube, Vimeo, etc.)', null=True, verbose_name='Event Video'),
        ),
    ]
