# Generated by Django 4.1 on 2025-11-05 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_team_city_alter_team_country_alter_team_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('player', 'Jugador'), ('parent', 'Padre/Acudiente'), ('team_manager', 'Manager de Equipo'), ('admin', 'Administrador')], default='player', max_length=20, verbose_name='Tipo de Usuario'),
        ),
        migrations.CreateModel(
            name='PlayerParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'Padre'), ('mother', 'Madre'), ('guardian', 'Acudiente'), ('other', 'Otro')], default='guardian', max_length=20, verbose_name='Relación')),
                ('is_primary', models.BooleanField(default=False, help_text='Marcar si es el contacto principal del jugador', verbose_name='Contacto Principal')),
                ('can_pickup', models.BooleanField(default=True, help_text='Marcar si esta persona puede recoger al jugador', verbose_name='Puede Recoger')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(limit_choices_to={'profile__user_type': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Padre/Acudiente')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='accounts.player', verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Padre/Acudiente de Jugador',
                'verbose_name_plural': 'Padres/Acudientes de Jugadores',
                'ordering': ['-is_primary', 'parent__last_name', 'parent__first_name'],
                'unique_together': {('parent', 'player')},
            },
        ),
    ]
