# Generated by Django 4.1 on 2025-11-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_player_age_verification_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, help_text='Año de graduación esperado (año actual o años futuros)', null=True, verbose_name='Año de Graduación'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age_verification_document',
            field=models.FileField(blank=True, help_text='Certificado de nacimiento o pasaporte', null=True, upload_to='accounts/age_verification/', verbose_name='Documento de Verificación de Edad'),
        ),
    ]
