# Generated by Django 4.1 on 2025-12-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_player_is_pitcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('infield', 'Infield'), ('outfield', 'Outfield'), ('utility', 'Utility')], max_length=20, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position_2',
            field=models.CharField(blank=True, choices=[('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('infield', 'Infield'), ('outfield', 'Outfield'), ('utility', 'Utility')], max_length=20, verbose_name='Posición 2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position_3',
            field=models.CharField(blank=True, choices=[('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('infield', 'Infield'), ('outfield', 'Outfield'), ('utility', 'Utility')], max_length=20, verbose_name='Posición 3'),
        ),
    ]
