# Generated by Django 4.1 on 2025-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_player_sports_shirt_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/player_photos/', verbose_name='Foto'),
        ),
    ]
