# Generated by Django 4.1 on 2025-12-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_player_graduation_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título del banner (opcional)', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción del banner (opcional)', verbose_name='Descripción')),
                ('banner_type', models.CharField(choices=[('image', 'Imagen'), ('gradient', 'Gradiente con Texto')], default='image', max_length=20, verbose_name='Tipo de Banner')),
                ('image', models.ImageField(blank=True, help_text='Imagen del banner (requerido si tipo es "Imagen")', null=True, upload_to='banners/', verbose_name='Imagen')),
                ('gradient_color_1', models.CharField(default='#0d2c54', help_text='Color hexadecimal (ej: #0d2c54)', max_length=7, verbose_name='Color Gradiente 1')),
                ('gradient_color_2', models.CharField(default='#132448', help_text='Color hexadecimal (ej: #132448)', max_length=7, verbose_name='Color Gradiente 2')),
                ('gradient_color_3', models.CharField(blank=True, help_text='Color hexadecimal opcional (ej: #64b5f6)', max_length=7, verbose_name='Color Gradiente 3')),
                ('button_text', models.CharField(blank=True, help_text='Texto del botón principal (opcional)', max_length=100, verbose_name='Texto del Botón')),
                ('button_url', models.CharField(blank=True, help_text='URL a donde lleva el botón (opcional)', max_length=500, verbose_name='URL del Botón')),
                ('button_text_2', models.CharField(blank=True, help_text='Texto del segundo botón (opcional)', max_length=100, verbose_name='Texto del Botón Secundario')),
                ('button_url_2', models.CharField(blank=True, help_text='URL del segundo botón (opcional)', max_length=500, verbose_name='URL del Botón Secundario')),
                ('icon_class', models.CharField(blank=True, help_text='Clase Font Awesome (ej: fa-trophy, fa-baseball-ball)', max_length=100, verbose_name='Clase del Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carousel', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner del Home',
                'verbose_name_plural': 'Banners del Home',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
