# Generated by Django 4.1 on 2025-12-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_image', models.ImageField(blank=True, help_text='Imagen que se muestra en la sección "Season Schedule" del home', null=True, upload_to='site_settings/', verbose_name='Imagen del Schedule')),
                ('schedule_title', models.CharField(default='CALENDARIO DE EVENTOS 2026', help_text='Título principal de la sección Schedule', max_length=200, verbose_name='Título del Schedule')),
                ('schedule_subtitle', models.CharField(default='EXPANSIÓN REGIONAL Y NUEVOS CAMPEONATOS NACIONALES Y REGIONALES PARA 2026', help_text='Subtítulo de la sección Schedule', max_length=300, verbose_name='Subtítulo del Schedule')),
                ('schedule_description', models.TextField(blank=True, help_text='Descripción de la sección Schedule', verbose_name='Descripción del Schedule')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
    ]
