# Generated by Django 4.1 on 2025-12-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_sitesettings_showcase_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la empresa o marca', max_length=200, verbose_name='Nombre del Sponsor')),
                ('logo', models.ImageField(help_text='Logo del sponsor (recomendado: formato PNG con fondo transparente)', upload_to='sponsors/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, help_text='URL del sitio web del sponsor (opcional)', null=True, verbose_name='URL del Sitio Web')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar este sponsor en el home', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número aparece primero)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['order', 'name'],
            },
        ),
    ]
