# Generated by Django 4.2.27 on 2025-12-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_dashboardbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcontent',
            name='user_type',
            field=models.CharField(choices=[('player', 'Jugador'), ('parent', 'Padre/Acudiente'), ('team_manager', 'Manager de Equipo'), ('all', 'Todos los Usuarios')], default='all', help_text='Seleccione para qué tipo de usuario es este contenido', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
