# Generated by Django 4.1 on 2025-12-28 02:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0026_userprofile_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance actual de la billetera', max_digits=10, verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Billetera de Usuario',
                'verbose_name_plural': 'Billeteras de Usuario',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Depósito'), ('payment', 'Pago'), ('refund', 'Reembolso'), ('withdrawal', 'Retiro')], max_length=20, verbose_name='Tipo de Transacción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('description', models.CharField(blank=True, help_text='Descripción de la transacción', max_length=500, verbose_name='Descripción')),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Balance de la billetera después de esta transacción', max_digits=10, verbose_name='Balance Después')),
                ('reference_id', models.CharField(blank=True, help_text='ID de referencia externa (pago, evento, etc.)', max_length=100, verbose_name='ID de Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Transacción')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userwallet', verbose_name='Billetera')),
            ],
            options={
                'verbose_name': 'Transacción de Billetera',
                'verbose_name_plural': 'Transacciones de Billetera',
                'ordering': ['-created_at'],
            },
        ),
    ]
