# Generated by Django 4.2.27 on 2026-01-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_player_is_pitcher_player_secondary_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batting_glove_size',
            field=models.CharField(blank=True, choices=[('YS', 'YS (Youth Small)'), ('YM', 'YM (Youth Medium)'), ('YL', 'YL (Youth Large)'), ('YXL', 'YXL (Youth XLarge)'), ('AS', 'AS (Adult Small)'), ('AM', 'AM (Adult Medium)'), ('AL', 'AL (Adult Large)')], max_length=10, verbose_name='Talla de Guante de Bateo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_size',
            field=models.CharField(blank=True, choices=[('YXS', 'YXS (Youth Extra Small)'), ('YS', 'YS (Youth Small)'), ('YM', 'YM (Youth Medium)'), ('YL', 'YL (Youth Large)'), ('YXL', 'YXL (Youth XLarge)'), ('AS', 'AS (Adult Small)'), ('AM', 'AM (Adult Medium)'), ('AL', 'AL (Adult Large)'), ('AXL', 'AXL (Adult Extra Large)'), ('A2XL', 'A2XL (Adult 2 Extra Large)')], max_length=10, verbose_name='Talla de Jersey'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shorts_size',
            field=models.CharField(blank=True, choices=[('YS', 'YS (Youth Small)'), ('YM', 'YM (Youth Medium)'), ('YL', 'YL (Youth Large)'), ('YXL', 'YXL (Youth XLarge)'), ('AS', 'AS (Adult Small)'), ('AM', 'AM (Adult Medium)'), ('AL', 'AL (Adult Large)'), ('AXL', 'AXL (Adult Extra Large)'), ('A2XL', 'A2XL (Adult 2 Extra Large)')], max_length=10, verbose_name='Talla de Pantalones'),
        ),
    ]
