# Generated by Django 6.0 on 2026-01-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_player_batting_glove_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_name2',
            field=models.CharField(blank=True, help_text='Segundo apellido (opcional)', max_length=30, verbose_name='Segundo Apellido'),
        ),
    ]
