# Generated by Django 6.0 on 2026-01-07 22:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_merge_slug_and_banner'),
        ('events', '0028_add_banner_and_logo_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Número único de identificación de la orden', max_length=50, unique=True, verbose_name='Número de Orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('failed', 'Fallido')], default='pending', help_text='Estado actual de la orden', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('wallet', 'Billetera Digital'), ('cash', 'Efectivo'), ('bank_transfer', 'Transferencia Bancaria'), ('other', 'Otro')], default='stripe', max_length=20, verbose_name='Método de Pago')),
                ('stripe_session_id', models.CharField(blank=True, help_text='ID de la sesión de checkout de Stripe', max_length=255, verbose_name='ID de Sesión de Stripe')),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID del payment intent de Stripe', max_length=255, verbose_name='ID de Payment Intent de Stripe')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='ID del cliente en Stripe', max_length=255, verbose_name='ID de Cliente de Stripe')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal antes de impuestos y descuentos', max_digits=10, verbose_name='Subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del descuento aplicado', max_digits=10, verbose_name='Descuento')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de impuestos (IVA, ISH, etc.)', max_digits=10, verbose_name='Impuestos')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total de la orden', max_digits=10, verbose_name='Total')),
                ('currency', models.CharField(default='usd', help_text='Moneda de la orden', max_length=10, verbose_name='Moneda')),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Desglose detallado de la orden (jugadores, habitaciones, servicios, etc.)', verbose_name='Desglose')),
                ('registered_player_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs de jugadores registrados en el evento', verbose_name='IDs de Jugadores Registrados')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la orden', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se completó el pago', null=True, verbose_name='Fecha de Pago')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('event', models.ForeignKey(blank=True, help_text='Evento relacionado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='events.event', verbose_name='Evento')),
                ('stripe_checkout', models.ForeignKey(blank=True, help_text='Checkout de Stripe relacionado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.stripeeventcheckout', verbose_name='Checkout de Stripe')),
                ('user', models.ForeignKey(help_text='Usuario que realiza la compra', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='accounts_or_order_n_003176_idx'), models.Index(fields=['user', '-created_at'], name='accounts_or_user_id_2d581e_idx'), models.Index(fields=['status', '-created_at'], name='accounts_or_status_b4537e_idx'), models.Index(fields=['stripe_session_id'], name='accounts_or_stripe__099efe_idx')],
            },
        ),
    ]
