# Generated by Django 6.0 on 2026-01-07 22:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_create_order_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('plan', 'Plan de Pagos'), ('now', 'Pago Único')], default='now', help_text='Si es plan de pagos o pago único', max_length=10, verbose_name='Modo de Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_monthly_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto a pagar mensualmente en el plan', max_digits=10, verbose_name='Monto Mensual'),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_months',
            field=models.PositiveIntegerField(default=1, help_text='Número de meses del plan de pagos (1 = pago único)', verbose_name='Meses del Plan'),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_payments_completed',
            field=models.PositiveIntegerField(default=0, help_text='Número de pagos completados del plan', verbose_name='Pagos Completados'),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_payments_remaining',
            field=models.PositiveIntegerField(default=0, help_text='Número de pagos pendientes del plan', verbose_name='Pagos Pendientes'),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total del plan de pagos (plan_months * plan_monthly_amount)', max_digits=10, verbose_name='Total del Plan'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='ID de la suscripción en Stripe (para planes de pago)', max_length=255, verbose_name='ID de Suscripción de Stripe'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_subscription_schedule_id',
            field=models.CharField(blank=True, help_text='ID del schedule de la suscripción en Stripe (para planes de pago)', max_length=255, verbose_name='ID de Schedule de Suscripción de Stripe'),
        ),
    ]
