# Generated by Django 6.0 on 2026-01-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_player_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('player', 'Jugador'), ('parent', 'Padre/Acudiente'), ('team_manager', 'Manager de Equipo'), ('spectator', 'Espectador'), ('admin', 'Administrador')], default='player', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
