# Generated by Django 6.0 on 2026-01-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_add_spectator_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('plan', 'Plan de Pagos'), ('now', 'Pago Único'), ('register_only', 'Registrar ahora, pagar después')], default='now', help_text='Si es plan de pagos, pago único o registro sin pago inmediato', max_length=20, verbose_name='Modo de Pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('pending_registration', 'Registrado - Pago Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('failed', 'Fallido')], default='pending', help_text='Estado actual de la orden', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='stripeeventcheckout',
            name='payment_mode',
            field=models.CharField(choices=[('plan', 'Plan'), ('now', 'Pay now'), ('register_only', 'Register now, pay later')], default='plan', max_length=20),
        ),
        migrations.AlterField(
            model_name='stripeeventcheckout',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('registered', 'Registered - Payment Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='created', max_length=20),
        ),
    ]
