# Generated by Django 6.0 on 2026-01-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_order_payment_mode_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeeventcheckout',
            name='currency',
        ),
        migrations.AddField(
            model_name='stripeeventcheckout',
            name='curstripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripeeventcheckout',
            name='hotel_stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
