# Generated by Django 6.0 on 2026-01-12 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_stripeeventcheckout_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffWalletTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Debe ser mayor a 0.00', max_digits=10, verbose_name='Monto a agregar')),
                ('description', models.CharField(blank=True, help_text='Motivo del ajuste (opcional)', max_length=500, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('created_by', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='created_wallet_topups', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_wallet_topups', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recarga de billetera (Staff)',
                'verbose_name_plural': 'Recargas de billetera (Staff)',
                'ordering': ['-created_at'],
            },
        ),
    ]
