# Generated by Django 6.0 on 2026-01-12 17:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_staffwallettopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance reservado para checkouts pendientes de pago', max_digits=10, verbose_name='Balance Pendiente'),
        ),
    ]
