# Generated by Django 6.0 on 2026-01-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_add_pending_balance_to_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('pending_registration', 'Registrado - Pago Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('failed', 'Fallido'), ('abandoned', 'Abandonado (Checkout no completado)')], default='pending', help_text='Estado actual de la orden', max_length=20, verbose_name='Estado'),
        ),
    ]
