# Generated by Django 6.0 on 2026-01-12 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_add_abandoned_order_status'),
        ('events', '0038_add_banner_mobile_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order', 'Orden'), ('event', 'Evento'), ('payment', 'Pago'), ('registration', 'Registro'), ('reminder', 'Recordatorio'), ('system', 'Sistema'), ('message', 'Mensaje')], default='system', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('action_url', models.URLField(blank=True, help_text='URL a la que redirigir cuando se hace clic en la notificación', null=True, verbose_name='URL de Acción')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='events.event', verbose_name='Evento')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.order', verbose_name='Orden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='accounts_no_user_id_9f7535_idx'), models.Index(fields=['user', '-created_at'], name='accounts_no_user_id_b37b35_idx')],
            },
        ),
    ]
