# Generated by Django 6.0 on 2026-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Notificaciones por Email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='event_notifications',
            field=models.BooleanField(default=True, verbose_name='Notificaciones de Eventos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_notifications',
            field=models.BooleanField(default=False, verbose_name='Notificaciones de Marketing'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reservation_notifications',
            field=models.BooleanField(default=True, verbose_name='Notificaciones de Reservas'),
        ),
    ]
