# Generated by Django 6.0 on 2026-01-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_userprofile_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='ID del cliente en Stripe para facturación', max_length=255, verbose_name='ID de Cliente de Stripe'),
        ),
    ]
