# Generated by Django 6.0 on 2026-01-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_pushsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='accounts_pu_user_id_125f9c_idx',
            old_name='accounts_pu_user_id_2db9b6_idx',
        ),
    ]
