# Generated by Django 6.0 on 2026-01-16 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_admintodo'),
        ('events', '0040_alter_event_video_url'),
        ('locations', '0029_siteimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmailBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('html_body', models.TextField(verbose_name='HTML Body')),
                ('send_to_parents', models.BooleanField(default=False)),
                ('send_to_managers', models.BooleanField(default=False)),
                ('send_to_spectators', models.BooleanField(default=False)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('recipient_emails', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_email_broadcasts', to='locations.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_email_broadcasts', to='locations.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_email_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_email_broadcasts', to='events.division')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_email_broadcasts', to='locations.state')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
