# Generated by Django 6.0 on 2026-01-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_adminemailbroadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminemailbroadcast',
            name='city_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adminemailbroadcast',
            name='country_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adminemailbroadcast',
            name='division_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adminemailbroadcast',
            name='state_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
