# Generated by Django 4.1 on 2025-11-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_site_city'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección Línea 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Secundario'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_media',
            field=models.CharField(blank=True, help_text='Instagram, Twitter, etc.', max_length=200, verbose_name='Redes Sociales'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='locations.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='locations.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='locations.state', verbose_name='Estado'),
        ),
    ]
