# Generated by Django 4.1 on 2025-11-05 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_site_city'),
        ('accounts', '0002_userprofile_address_line_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='locations.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='locations.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='locations.state', verbose_name='Estado'),
        ),
    ]
