# Generated by Django 4.1 on 2025-11-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_user_type_playerparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bienvenido', max_length=200, verbose_name='Título')),
                ('content', models.TextField(help_text='Contenido HTML permitido', verbose_name='Contenido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido del Dashboard',
                'verbose_name_plural': 'Contenidos del Dashboard',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
