# Generated by Django 4.1 on 2025-11-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dashboardcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='batting_glove_size',
            field=models.CharField(blank=True, choices=[('YS', 'YS (Youth Small)'), ('YM', 'YM (Youth Medium)'), ('YL', 'YL (Youth Large)'), ('AS', 'AS (Adult Small)'), ('AM', 'AM (Adult Medium)'), ('AL', 'AL (Adult Large)')], max_length=10, verbose_name='Talla de Guante de Bateo'),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_helmet_size',
            field=models.CharField(blank=True, choices=[('XS', 'X-Small'), ('SM', 'Small / Medium'), ('ML', 'Medium / Large'), ('L_XL', 'Large / X-Large')], max_length=10, verbose_name='Talla de Casco de Bateo'),
        ),
        migrations.AddField(
            model_name='player',
            name='hat_size',
            field=models.CharField(blank=True, choices=[('XS_S', 'X-Small / Small'), ('SM', 'Small-Medium'), ('L_XL', 'Large / X-Large')], max_length=10, verbose_name='Talla de Gorra'),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_size',
            field=models.CharField(blank=True, choices=[('YXS', 'YXS (Youth Extra Small)'), ('YS', 'YS (Youth Small)'), ('YM', 'YM (Youth Medium)'), ('YL', 'YL (Youth Large)'), ('AS', 'AS (Adult Small)'), ('AM', 'AM (Adult Medium)'), ('AL', 'AL (Adult Large)'), ('AXL', 'AXL (Adult Extra Large)'), ('A2XL', 'A2XL (Adult 2 Extra Large)')], max_length=10, verbose_name='Talla de Jersey'),
        ),
        migrations.AddField(
            model_name='player',
            name='shorts_size',
            field=models.CharField(blank=True, choices=[('YS', 'YS (Youth Small)'), ('YM', 'YM (Youth Medium)'), ('YL', 'YL (Youth Large)'), ('AS', 'AS (Adult Small)'), ('AM', 'AM (Adult Medium)'), ('AL', 'AL (Adult Large)'), ('AXL', 'AXL (Adult Extra Large)'), ('A2XL', 'A2XL (Adult 2 Extra Large)')], max_length=10, verbose_name='Talla de Pantalones'),
        ),
    ]
