# Generated by Django 4.1 on 2025-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_player_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position_2',
            field=models.CharField(blank=True, choices=[('pitcher', 'Pitcher'), ('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('designated_hitter', 'Designated Hitter'), ('utility', 'Utility')], max_length=20, verbose_name='Posición 2'),
        ),
        migrations.AddField(
            model_name='player',
            name='position_3',
            field=models.CharField(blank=True, choices=[('pitcher', 'Pitcher'), ('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('designated_hitter', 'Designated Hitter'), ('utility', 'Utility')], max_length=20, verbose_name='Posición 3'),
        ),
    ]
