# Generated by Django 4.1 on 2025-12-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_player_position_2_player_position_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_pitcher',
            field=models.BooleanField(default=False, verbose_name='¿Es Pitcher?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('utility', 'Utility')], max_length=20, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position_2',
            field=models.CharField(blank=True, choices=[('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('utility', 'Utility')], max_length=20, verbose_name='Posición 2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position_3',
            field=models.CharField(blank=True, choices=[('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('utility', 'Utility')], max_length=20, verbose_name='Posición 3'),
        ),
    ]
