# Generated by Django 4.1 on 2025-12-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_description',
            field=models.TextField(blank=True, help_text='Descripción de la sección Showcase', verbose_name='Descripción del Showcase'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_image',
            field=models.ImageField(blank=True, help_text='Imagen que se muestra en la sección "Showcases and Prospect Gateways" del home', null=True, upload_to='site_settings/', verbose_name='Imagen del Showcase'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_subtitle',
            field=models.CharField(default='REGIONAL AND NATIONAL SHOWCASES', help_text='Subtítulo de la sección Showcase', max_length=300, verbose_name='Subtítulo del Showcase'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_title',
            field=models.CharField(default='SHOWCASES AND PROSPECT GATEWAYS', help_text='Título principal de la sección Showcase', max_length=200, verbose_name='Título del Showcase'),
        ),
    ]
