# Generated by Django 4.1 on 2025-12-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_sitesettings_dashboard_welcome_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título del banner (opcional)', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción del banner (opcional)', verbose_name='Descripción')),
                ('banner_type', models.CharField(choices=[('image', 'Imagen'), ('gradient', 'Gradiente con Texto')], default='image', max_length=20, verbose_name='Tipo de Banner')),
                ('image', models.ImageField(blank=True, help_text='Imagen del banner (requerido si tipo es "Imagen")', null=True, upload_to='dashboard_banners/', verbose_name='Imagen')),
                ('gradient_color_1', models.CharField(default='#0d2c54', help_text='Color hexadecimal (ej: #0d2c54)', max_length=7, verbose_name='Color Gradiente 1')),
                ('gradient_color_2', models.CharField(default='#132448', help_text='Color hexadecimal (ej: #132448)', max_length=7, verbose_name='Color Gradiente 2')),
                ('gradient_color_3', models.CharField(blank=True, help_text='Color hexadecimal opcional (ej: #64b5f6)', max_length=7, verbose_name='Color Gradiente 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número aparece primero)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner del Panel',
                'verbose_name_plural': 'Banners del Panel',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
