# Generated by Django 4.1 on 2026-01-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_stripeeventcheckout_amount_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Message text to display in the marquee', max_length=500, verbose_name='Message')),
                ('is_active', models.BooleanField(default=True, help_text='Only active messages will be displayed', verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance (lower numbers appear first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marquee Message',
                'verbose_name_plural': 'Marquee Messages',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
