# Generated by Django 4.1 on 2025-11-05 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('player', 'Jugador'), ('team_manager', 'Manager de Equipo'), ('admin', 'Administrador')], default='player', max_length=20, verbose_name='Tipo de Usuario')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='accounts/profile_pictures/', verbose_name='Foto de Perfil')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Equipo')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='accounts/team_logos/', verbose_name='Logo del Equipo')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(limit_choices_to={'profile__user_type': 'team_manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Jersey')),
                ('position', models.CharField(blank=True, choices=[('pitcher', 'Pitcher'), ('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('designated_hitter', 'Designated Hitter'), ('utility', 'Utility')], max_length=20, verbose_name='Posición')),
                ('height', models.CharField(blank=True, max_length=10, verbose_name='Estatura (ej: 5\'10")')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso (lbs)')),
                ('batting_hand', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('S', 'Switch')], max_length=1, verbose_name='Bateo')),
                ('throwing_hand', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, verbose_name='Lanzamiento')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de Contacto de Emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Emergencia')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='Relación')),
                ('medical_conditions', models.TextField(blank=True, help_text='Información médica relevante', verbose_name='Condiciones Médicas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='accounts.team', verbose_name='Equipo')),
                ('user', models.OneToOneField(limit_choices_to={'profile__user_type': 'player'}, on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
