# Generated by Django 4.1 on 2025-11-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_player_batting_glove_size_player_batting_helmet_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age_verification_approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación de Verificación'),
        ),
        migrations.AddField(
            model_name='player',
            name='age_verification_document',
            field=models.FileField(blank=True, help_text='Certificado de nacimiento, pasaporte o ID (original o digital)', null=True, upload_to='accounts/age_verification/', verbose_name='Documento de Verificación de Edad'),
        ),
        migrations.AddField(
            model_name='player',
            name='age_verification_notes',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la verificación de edad', verbose_name='Notas de Verificación'),
        ),
        migrations.AddField(
            model_name='player',
            name='age_verification_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado de Verificación de Edad'),
        ),
        migrations.AddField(
            model_name='player',
            name='division',
            field=models.CharField(blank=True, choices=[('05U', '05U'), ('06U', '06U'), ('07U', '07U'), ('08U', '08U'), ('09U', '09U'), ('10U', '10U'), ('11U', '11U'), ('12U', '12U'), ('13U', '13U'), ('14U', '14U'), ('15U', '15U'), ('16U', '16U'), ('17U', '17U'), ('18U', '18U')], help_text='División en la que el jugador está asignado', max_length=10, verbose_name='División Asignada'),
        ),
        migrations.AddField(
            model_name='player',
            name='grade',
            field=models.CharField(blank=True, choices=[('pre_k', 'Pre-K'), ('kindergarten', 'Kindergarten'), ('1st', '1st Grade'), ('2nd', '2nd Grade'), ('3rd', '3rd Grade'), ('4th', '4th Grade'), ('5th', '5th Grade'), ('6th', '6th Grade'), ('7th', '7th Grade'), ('8th', '8th Grade'), ('9th', '9th Grade'), ('10th', '10th Grade'), ('11th', '11th Grade'), ('12th', '12th Grade')], help_text='Grado escolar actual del jugador', max_length=20, verbose_name='Grado Actual'),
        ),
    ]
