# Generated by Django 4.1 on 2025-12-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_player_is_pitcher_alter_player_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_pitcher',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, verbose_name='¿Es Pitcher?'),
        ),
    ]
