# Generated by Django 4.1 on 2025-12-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_player_position_alter_player_position_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shorts_size_select',
            field=models.CharField(blank=True, choices=[('YS', 'YS (Youth Small)'), ('YM', 'YM (Youth Medium)'), ('YL', 'YL (Youth Large)'), ('AS', 'AS (Adult Small)'), ('AM', 'AM (Adult Medium)'), ('AL', 'AL (Adult Large)'), ('AXL', 'AXL (Adult Extra Large)'), ('A2XL', 'A2XL (Adult 2 Extra Large)')], max_length=10, verbose_name='Talla de Shorts'),
        ),
    ]
