# Generated by Django 4.1 on 2025-12-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_player_shorts_size_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sports_shirt_size',
            field=models.CharField(blank=True, choices=[('YXS', 'YXS (Youth Extra Small)'), ('YS', 'YS (Youth Small)'), ('YM', 'YM (Youth Medium)'), ('YL', 'YL (Youth Large)'), ('AS', 'AS (Adult Small)'), ('AM', 'AM (Adult Medium)'), ('AL', 'AL (Adult Large)'), ('AXL', 'AXL (Adult Extra Large)'), ('A2XL', 'A2XL (Adult 2 Extra Large)')], max_length=10, verbose_name='Talla de camiseta deportiva'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shorts_size_select',
            field=models.CharField(blank=True, choices=[('YS', 'YS (Youth Small)'), ('YM', 'YM (Youth Medium)'), ('YL', 'YL (Youth Large)'), ('AS', 'AS (Adult Small)'), ('AM', 'AM (Adult Medium)'), ('AL', 'AL (Adult Large)'), ('AXL', 'AXL (Adult Extra Large)'), ('A2XL', 'A2XL (Adult 2 Extra Large)')], max_length=10, verbose_name='Talla de Shorts deportivos'),
        ),
    ]
