# Generated by Django 4.1 on 2025-12-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_player_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_pitcher',
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position_2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position_3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shorts_size_select',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sports_shirt_size',
        ),
        migrations.AlterField(
            model_name='player',
            name='age_verification_document',
            field=models.FileField(blank=True, help_text='Certificado de nacimiento, pasaporte o ID (original o digital)', null=True, upload_to='accounts/age_verification/', verbose_name='Documento de Verificación de Edad'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('pitcher', 'Pitcher'), ('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('designated_hitter', 'Designated Hitter'), ('utility', 'Utility')], max_length=20, verbose_name='Posición'),
        ),
    ]
