# Generated by Django 4.1 on 2025-12-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_welcome_banner',
            field=models.ImageField(blank=True, help_text='Imagen que se muestra en el welcome banner del panel de usuario (/accounts/panel/)', null=True, upload_to='site_settings/', verbose_name='Banner de Bienvenida del Panel'),
        ),
    ]
