# Generated by Django 4.2.27 on 2025-12-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_dashboardcontent_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_description_en',
            field=models.TextField(blank=True, default='As we move forward into 2026, NSC International continues to elevate its tournament and showcase platform. With a regional presence expansion for ages 7U-18U, new and improved National and Regional Championship events, and an even broader showcase schedule across the country, NSC remains dedicated to providing the highest standard of competition and experience for players, coaches and families alike.', help_text='Descripción de la sección Schedule en inglés', verbose_name='Schedule Description (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_description_es',
            field=models.TextField(blank=True, default='A medida que avanzamos hacia 2026, NSC International continúa elevando su plataforma de torneos y exhibiciones. Con una expansión de la presencia regional para edades 7U-18U, nuevos y mejorados eventos de Campeonatos Nacionales y Regionales, y una programación aún más amplia de exhibiciones en todo el país, NSC se mantiene dedicado a ofrecer el más alto estándar de competencia y experiencia para jugadores, entrenadores y familias por igual.', help_text='Descripción de la sección Schedule en español', verbose_name='Schedule Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_subtitle_en',
            field=models.CharField(default='REGIONAL EXPANSION AND NEW NATIONAL AND REGIONAL CHAMPIONSHIPS FOR 2026', help_text='Subtítulo de la sección Schedule en inglés', max_length=300, verbose_name='Schedule Subtitle (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_subtitle_es',
            field=models.CharField(default='EXPANSIÓN REGIONAL Y NUEVOS CAMPEONATOS NACIONALES Y REGIONALES PARA 2026', help_text='Subtítulo de la sección Schedule en español', max_length=300, verbose_name='Schedule Subtitle (Spanish)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_title_en',
            field=models.CharField(default='2026 EVENT CALENDAR', help_text='Título principal de la sección Schedule en inglés', max_length=200, verbose_name='Schedule Title (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_title_es',
            field=models.CharField(default='CALENDARIO DE EVENTOS 2026', help_text='Título principal de la sección Schedule en español', max_length=200, verbose_name='Schedule Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_description_en',
            field=models.TextField(blank=True, default='Perfect Game is thrilled to offer showcases (HS) and Prospect Gateways (13U/14U) across the country for the 2025 calendar. This includes regional events for all ages and new invite only events! PG strives to delivery the very best events and experience for all players, coaches and families across the country.', help_text='Descripción de la sección Showcase en inglés', verbose_name='Showcase Description (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_description_es',
            field=models.TextField(blank=True, default='Perfect Game se complace en ofrecer showcases (HS) y Prospect Gateways (13U/14U) en todo el país para el calendario 2025. Esto incluye eventos regionales para todas las edades y nuevos eventos solo por invitación. PG se esfuerza por ofrecer los mejores eventos y experiencias para todos los jugadores, entrenadores y familias en todo el país.', help_text='Descripción de la sección Showcase en español', verbose_name='Showcase Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_subtitle_en',
            field=models.CharField(default='REGIONAL AND NATIONAL SHOWCASES', help_text='Subtítulo de la sección Showcase en inglés', max_length=300, verbose_name='Showcase Subtitle (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_subtitle_es',
            field=models.CharField(default='SHOWCASES REGIONALES Y NACIONALES', help_text='Subtítulo de la sección Showcase en español', max_length=300, verbose_name='Showcase Subtitle (Spanish)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_title_en',
            field=models.CharField(default='SHOWCASES AND PROSPECT GATEWAYS', help_text='Título principal de la sección Showcase en inglés', max_length=200, verbose_name='Showcase Title (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_title_es',
            field=models.CharField(default='SHOWCASES Y PORTALES DE PROSPECTO', help_text='Título principal de la sección Showcase en español', max_length=200, verbose_name='Showcase Title (Spanish)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='schedule_description',
            field=models.TextField(blank=True, editable=False, help_text='[DEPRECATED] Usar schedule_description_en y schedule_description_es', verbose_name='Descripción del Schedule (Legacy)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='schedule_subtitle',
            field=models.CharField(default='REGIONAL EXPANSION AND NEW NATIONAL AND REGIONAL CHAMPIONSHIPS FOR 2026', editable=False, help_text='[DEPRECATED] Usar schedule_subtitle_en y schedule_subtitle_es', max_length=300, verbose_name='Subtítulo del Schedule (Legacy)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='schedule_title',
            field=models.CharField(default='2026 EVENT CALENDAR', editable=False, help_text='[DEPRECATED] Usar schedule_title_en y schedule_title_es', max_length=200, verbose_name='Título del Schedule (Legacy)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='showcase_description',
            field=models.TextField(blank=True, editable=False, help_text='[DEPRECATED] Usar showcase_description_en y showcase_description_es', verbose_name='Descripción del Showcase (Legacy)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='showcase_subtitle',
            field=models.CharField(default='REGIONAL AND NATIONAL SHOWCASES', editable=False, help_text='[DEPRECATED] Usar showcase_subtitle_en y showcase_subtitle_es', max_length=300, verbose_name='Subtítulo del Showcase (Legacy)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='showcase_title',
            field=models.CharField(default='SHOWCASES AND PROSPECT GATEWAYS', editable=False, help_text='[DEPRECATED] Usar showcase_title_en y showcase_title_es', max_length=200, verbose_name='Título del Showcase (Legacy)'),
        ),
    ]
