# Generated by Django 4.1 on 2025-12-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_multilanguage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, help_text='Dirección o ubicación que se muestra en el footer', max_length=200, verbose_name='Dirección de Contacto'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email que se muestra en el footer', max_length=254, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Teléfono que se muestra en el footer', max_length=50, verbose_name='Teléfono de Contacto'),
        ),
    ]
