# Generated by Django 4.1 on 2025-12-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_sitesettings_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text='Idioma predeterminado para la plataforma', max_length=10, verbose_name='Idioma Preferido'),
        ),
    ]
