# Generated by Django 4.1 on 2026-01-03 00:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_stripe_event_checkout_subscription_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeeventcheckout',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
