# Generated by Django 4.1 on 2026-01-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_marqueemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_pitcher',
            field=models.BooleanField(default=False, help_text='Check if the player is a pitcher', verbose_name='Are you a pitcher?'),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_position',
            field=models.CharField(blank=True, choices=[('pitcher', 'Pitcher'), ('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('designated_hitter', 'Designated Hitter'), ('utility', 'Utility')], help_text='Secondary position the player can play', max_length=20, verbose_name='Secondary Position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('pitcher', 'Pitcher'), ('catcher', 'Catcher'), ('first_base', 'First Base'), ('second_base', 'Second Base'), ('third_base', 'Third Base'), ('shortstop', 'Shortstop'), ('left_field', 'Left Field'), ('center_field', 'Center Field'), ('right_field', 'Right Field'), ('designated_hitter', 'Designated Hitter'), ('utility', 'Utility')], max_length=20, verbose_name='Primary Position'),
        ),
    ]
