# Generated by Django 6.0 on 2026-01-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_userprofile_last_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Imagen del banner para dispositivos móviles (opcional, si no se proporciona se usará la imagen principal)', null=True, upload_to='banners/mobile/', verbose_name='Imagen Móvil'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del banner para desktop (requerido si tipo es "Imagen")', null=True, upload_to='banners/', verbose_name='Imagen'),
        ),
    ]
