# Generated by Django 5.0.6 on 2025-09-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='league',
            field=models.CharField(blank=True, max_length=100, verbose_name='Liga'),
        ),
        migrations.AddField(
            model_name='season',
            name='season_type',
            field=models.CharField(choices=[('regular', 'Temporada Regular'), ('playoffs', 'Playoffs'), ('world_series', 'Serie Mundial'), ('all_star', 'Juego de Estrellas'), ('spring_training', 'Entrenamiento de Primavera'), ('winter_league', 'Liga de Invierno'), ('international', 'Competencia Internacional')], default='regular', max_length=20, verbose_name='Tipo de Temporada'),
        ),
        migrations.AddField(
            model_name='season',
            name='teams_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Equipos'),
        ),
        migrations.AddField(
            model_name='season',
            name='total_games',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de Juegos'),
        ),
    ]
