# Generated by Django 5.0.6 on 2025-09-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_season_league_season_season_type_season_teams_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Rule Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('rule_type', models.CharField(choices=[('standard', 'Standard Rules'), ('modified', 'Modified Rules'), ('custom', 'Custom Rules'), ('championship', 'Championship Rules'), ('exhibition', 'Exhibition Rules')], default='standard', max_length=20, verbose_name='Rule Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'ordering': ['name'],
            },
        ),
    ]
