# Generated by Django 5.0.6 on 2025-09-24 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='Nombre del sitio o instalación', max_length=200, verbose_name='Site Name')),
                ('abbreviation', models.CharField(blank=True, help_text='Abreviatura del sitio', max_length=50, verbose_name='Abbreviation')),
                ('address_1', models.CharField(help_text='Dirección principal', max_length=200, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, help_text='Dirección secundaria (opcional)', max_length=200, verbose_name='Address 2')),
                ('city', models.CharField(help_text='Ciudad', max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(help_text='Código postal', max_length=20, verbose_name='Postal Code')),
                ('website', models.URLField(blank=True, help_text='Sitio web del lugar', verbose_name='Website')),
                ('additional_info', models.TextField(blank=True, help_text='Información adicional sobre el sitio (ej. Reglas del parque)', verbose_name='Additional Info')),
                ('image', models.ImageField(blank=True, help_text='Imagen principal del sitio', null=True, upload_to='sites/', verbose_name='Site Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='locations.country', verbose_name='Country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='locations.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['site_name'],
            },
        ),
    ]
