# Generated by Django 5.0.6 on 2025-09-24 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_site_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Ciudad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='locations.city', verbose_name='City'),
        ),
    ]
