# Generated by Django 4.1 on 2025-12-04 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_site_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(help_text='Nombre del hotel', max_length=200, verbose_name='Nombre del Hotel')),
                ('address', models.CharField(help_text='Dirección completa del hotel', max_length=500, verbose_name='Dirección')),
                ('photo', models.ImageField(blank=True, help_text='Foto del hotel', null=True, upload_to='hotels/', verbose_name='Foto')),
                ('information', models.TextField(blank=True, help_text='Información adicional sobre el hotel', verbose_name='Información')),
                ('registration_url', models.URLField(blank=True, help_text='URL para registro en el hotel', verbose_name='URL Hotel Registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('city', models.ForeignKey(blank=True, help_text='Ciudad donde se encuentra el hotel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='locations.city', verbose_name='Ciudad')),
                ('country', models.ForeignKey(blank=True, help_text='País donde se encuentra el hotel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='locations.country', verbose_name='País')),
                ('state', models.ForeignKey(blank=True, help_text='Estado donde se encuentra el hotel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='locations.state', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'ordering': ['hotel_name'],
            },
        ),
    ]
