# Generated by Django 4.1 on 2025-12-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Capacidad del hotel (número de habitaciones o personas)', null=True, verbose_name='Capacidad'),
        ),
    ]
