# Generated by Django 4.1 on 2025-12-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_hotel_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Correo electrónico de la persona de contacto', max_length=254, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Nombre de la persona de contacto del hotel', max_length=200, verbose_name='Nombre de Contacto'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Número de teléfono de la persona de contacto', max_length=20, verbose_name='Teléfono de Contacto'),
        ),
    ]
