# Generated by Django 4.1 on 2025-12-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_create_hotel_room_service_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen para la galería del hotel', upload_to='hotels/gallery/', verbose_name='Imagen')),
                ('title', models.CharField(blank=True, help_text='Título o descripción de la imagen', max_length=200, verbose_name='Título')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para accesibilidad', max_length=200, verbose_name='Texto Alternativo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)', verbose_name='Orden')),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar como imagen destacada/principal', verbose_name='Destacada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='locations.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Imagen de Hotel',
                'verbose_name_plural': 'Imágenes de Hotel',
                'ordering': ['hotel', 'order', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la amenidad', max_length=200, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('general', 'General'), ('room', 'Habitación'), ('bathroom', 'Baño'), ('entertainment', 'Entretenimiento'), ('food_drink', 'Comida y Bebida'), ('services', 'Servicios'), ('accessibility', 'Accesibilidad')], default='general', max_length=30, verbose_name='Categoría')),
                ('icon', models.CharField(choices=[('wifi', 'WiFi'), ('parking', 'Estacionamiento'), ('pool', 'Piscina'), ('gym', 'Gimnasio'), ('spa', 'Spa'), ('restaurant', 'Restaurante'), ('bar', 'Bar'), ('room_service', 'Servicio a Habitación'), ('air_conditioning', 'Aire Acondicionado'), ('heating', 'Calefacción'), ('tv', 'Televisión'), ('safe', 'Caja Fuerte'), ('minibar', 'Minibar'), ('balcony', 'Balcón'), ('hairdryer', 'Secador de Pelo'), ('bathtub', 'Bañera'), ('shower', 'Ducha'), ('cable_tv', 'TV por Cable'), ('streaming', 'Streaming'), ('game_room', 'Sala de Juegos'), ('laundry', 'Lavandería'), ('concierge', 'Concierge'), ('24h_reception', 'Recepción 24h'), ('airport_shuttle', 'Transporte Aeropuerto'), ('business_center', 'Centro de Negocios'), ('meeting_rooms', 'Salas de Reuniones'), ('wheelchair_accessible', 'Acceso para Sillas de Ruedas'), ('elevator', 'Ascensor'), ('pet_friendly', 'Admite Mascotas'), ('smoking_area', 'Área de Fumadores'), ('non_smoking', 'No Fumadores'), ('family_friendly', 'Apto para Familias'), ('other', 'Otro')], default='other', help_text='Ícono representativo de la amenidad', max_length=30, verbose_name='Ícono')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la amenidad', verbose_name='Descripción')),
                ('is_available', models.BooleanField(default=True, help_text='Indica si la amenidad está disponible actualmente', verbose_name='Disponible')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='locations.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Amenidad de Hotel',
                'verbose_name_plural': 'Amenidades de Hotel',
                'ordering': ['hotel', 'category', 'order', 'name'],
            },
        ),
    ]
