# Generated by Django 4.1 on 2025-12-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_hotelimage_hotelamenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen para la galería de la habitación', upload_to='hotels/rooms/gallery/', verbose_name='Imagen')),
                ('title', models.CharField(blank=True, help_text='Título o descripción de la imagen', max_length=200, verbose_name='Título')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para accesibilidad', max_length=200, verbose_name='Texto Alternativo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('is_featured', models.BooleanField(default=False, help_text='Marca esta imagen como destacada', verbose_name='Destacada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='locations.hotelroom', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Imagen de Habitación',
                'verbose_name_plural': 'Imágenes de Habitaciones',
                'ordering': ['room', 'order', '-is_featured', '-created_at'],
            },
        ),
    ]
