# Generated by Django 4.1 on 2025-12-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_hotelroomimage_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='max_adults',
            field=models.PositiveIntegerField(default=2, help_text='Número máximo de adultos que puede alojar esta habitación', verbose_name='Adultos Máximos'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='min_adults',
            field=models.PositiveIntegerField(default=1, help_text='Número mínimo de adultos requeridos para esta habitación', verbose_name='Adultos Mínimos'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre descriptivo de la habitación (ej: Suite Presidencial, Habitación con Vista al Mar)', max_length=200, verbose_name='Nombre de la Habitación'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Número máximo de personas que puede alojar (incluyendo adultos y niños)', verbose_name='Capacidad Total'),
        ),
    ]
