# Generated by Django 4.1 on 2025-12-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_hotelroom_max_adults_hotelroom_min_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='max_children',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de niños que puede alojar esta habitación', verbose_name='Niños Máximos'),
        ),
    ]
