# Generated by Django 4.1 on 2025-12-28 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_hotelroom_max_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_adults', models.PositiveIntegerField(help_text='Número mínimo de adultos requeridos en esta regla', verbose_name='Adultos Mínimos')),
                ('max_adults', models.PositiveIntegerField(help_text='Número máximo de adultos permitidos en esta regla', verbose_name='Adultos Máximos')),
                ('min_children', models.PositiveIntegerField(default=0, help_text='Número mínimo de niños requeridos en esta regla', verbose_name='Niños Mínimos')),
                ('max_children', models.PositiveIntegerField(default=0, help_text='Número máximo de niños permitidos en esta regla', verbose_name='Niños Máximos')),
                ('description', models.CharField(blank=True, help_text="Descripción opcional de esta regla (ej: 'Mínimo 1 niño y máximo 3 adultos')", max_length=200, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta regla está activa', verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='locations.hotelroom', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Regla de Habitación',
                'verbose_name_plural': 'Reglas de Habitación',
                'ordering': ['room', 'order', 'min_adults', 'min_children'],
            },
        ),
    ]
