# Generated by Django 4.1 on 2025-12-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_hotelroomrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='max_adults',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='max_children',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='min_adults',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='price_includes_guests',
            field=models.PositiveIntegerField(default=1, help_text='Número de personas incluidas en el precio por noche (si hay personas adicionales, puede haber un cargo extra)', verbose_name='Personas Incluidas en el Precio'),
        ),
    ]
