# Generated by Django 4.1 on 2025-12-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_add_price_includes_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='breakfast_included',
            field=models.BooleanField(default=False, help_text='Indica si el desayuno está incluido en el precio de la habitación', verbose_name='Desayuno Incluido'),
        ),
    ]
