# Generated by Django 4.1 on 2025-12-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_add_breakfast_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='additional_guest_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio adicional por noche por cada persona que exceda el número de personas incluidas en el precio base', max_digits=10, verbose_name='Precio por Persona Adicional'),
        ),
    ]
