# Generated by Django 4.1 on 2025-12-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_add_additional_guest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Amenidades específicas de esta habitación', related_name='rooms', to='locations.hotelamenity', verbose_name='Amenidades'),
        ),
    ]
