# Generated by Django 6.0 on 2026-01-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0020_hotelroom_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del impuesto (ej: IVA, Tasa Municipal)', max_length=100, verbose_name='Nombre del Impuesto')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto fijo del impuesto', max_digits=10, verbose_name='Monto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Impuesto de Habitación',
                'verbose_name_plural': 'Impuestos de Habitación',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de habitaciones disponibles de este tipo', verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='taxes',
            field=models.ManyToManyField(blank=True, help_text='Impuestos aplicables a esta habitación', related_name='rooms', to='locations.hotelroomtax', verbose_name='Impuestos'),
        ),
    ]
