# Generated by Django 6.0 on 2026-01-07 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_add_banner_and_logo_fields'),
        ('locations', '0021_hotelroomtax_hotelroom_stock_hotelroom_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomtax',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Opcional: Vincular este impuesto a un evento específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_taxes', to='events.event', verbose_name='Evento'),
        ),
    ]
