# Generated by Django 6.0 on 2026-01-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0022_hotelroomtax_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='buy_out_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cargo por no hospedarse en el hotel sede', max_digits=10, verbose_name='Buy Out Fee'),
        ),
    ]
