# Generated by Django 6.0 on 2026-01-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0023_hotel_buy_out_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='check_in_date',
            field=models.DateField(blank=True, help_text='Fecha sugerida de entrada para este tipo de habitación (opcional)', null=True, verbose_name='Fecha de Check-in'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='Hora de entrada (ej: 15:00) (opcional)', null=True, verbose_name='Hora de Check-in'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='check_out_date',
            field=models.DateField(blank=True, help_text='Fecha sugerida de salida para este tipo de habitación (opcional)', null=True, verbose_name='Fecha de Check-out'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Hora de salida (ej: 11:00) (opcional)', null=True, verbose_name='Hora de Check-out'),
        ),
    ]
