# Generated by Django 6.0 on 2026-01-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0024_hotelroom_checkin_checkout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreservation',
            name='additional_guest_names',
            field=models.TextField(blank=True, help_text='Nombres de los huéspedes adicionales (uno por línea). Ej: Juan Pérez\\nMaría Gómez', verbose_name='Nombres de Huéspedes Adicionales'),
        ),
    ]
