# Generated by Django 6.0 on 2026-01-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0025_hotelreservation_additional_guest_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreservation',
            name='additional_guest_details_json',
            field=models.JSONField(blank=True, default=list, help_text="Lista de huéspedes adicionales con información completa: nombre, tipo (adult/child), fecha de nacimiento y email. Ej: [{'name': 'María García', 'type': 'adult', 'birth_date': '1990-01-01', 'email': 'maria@example.com'}]", verbose_name='Detalles Completos de Huéspedes Adicionales'),
        ),
    ]
