# Generated by Django 6.0 on 2026-01-07 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_add_payment_plan_fields_to_order'),
        ('locations', '0026_add_additional_guest_details_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreservation',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Orden asociada a esta reserva (si fue comprada a través de una orden)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_reservations_direct', to='accounts.order', verbose_name='Orden'),
        ),
    ]
