# Generated by Django 6.0 on 2026-01-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0027_add_order_to_hotel_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='image',
            field=models.URLField(blank=True, help_text='URL de la imagen principal del sitio (desde biblioteca multimedia)', null=True, verbose_name='Site Image'),
        ),
    ]
