# Generated by Django 4.1 on 2025-12-27 18:48

import apps.media.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo del archivo', max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del archivo', null=True, verbose_name='Descripción')),
                ('original_file', models.FileField(help_text='Archivo original subido', storage=django.core.files.storage.FileSystemStorage(base_url='/multimedia/', location='C:\\Users\\User\\Documents\\NCS 2\\NSC-INTERNATIONAL\\multimedia'), upload_to=apps.media.models.multimedia_upload_path, verbose_name='Archivo Original')),
                ('processed_file', models.FileField(blank=True, help_text='Archivo procesado (ej: imagen WebP comprimida)', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/multimedia/', location='C:\\Users\\User\\Documents\\NCS 2\\NSC-INTERNATIONAL\\multimedia'), upload_to=apps.media.models.multimedia_upload_path, verbose_name='Archivo Procesado')),
                ('file_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('document', 'Documento'), ('audio', 'Audio'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de Archivo')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño del Archivo (bytes)')),
                ('processed_file_size', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tamaño del Archivo Procesado (bytes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancho (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Alto (px)')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para accesibilidad (alt text)', max_length=255, verbose_name='Texto Alternativo')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado'), ('deleted', 'Eliminado')], default='active', max_length=20, verbose_name='Estado')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas para organización', max_length=500, verbose_name='Etiquetas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo Multimedia',
                'verbose_name_plural': 'Archivos Multimedia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type', 'status'], name='media_media_file_ty_f09fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['created_at'], name='media_media_created_74471a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by'], name='media_media_uploade_dbbf17_idx'),
        ),
    ]
