# Generated by Django 4.1 on 2025-12-27 19:14

import apps.media.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Miniatura del archivo (generada automáticamente para videos)', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/multimedia/', location='C:\\Users\\User\\Documents\\NCS 2\\NSC-INTERNATIONAL\\multimedia'), upload_to=apps.media.models.multimedia_upload_path, verbose_name='Miniatura'),
        ),
    ]
