# Generated by Django 4.1 on 2026-01-03 00:04

import apps.media.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediafile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='original_file',
            field=models.FileField(help_text='Archivo original subido', storage=django.core.files.storage.FileSystemStorage(base_url='/mnt/volume_sfo3_02/multimedia/', location='C:\\Users\\User\\Documents\\NCS 2\\NSC-INTERNATIONAL\\multimedia'), upload_to=apps.media.models.multimedia_upload_path, verbose_name='Archivo Original'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='processed_file',
            field=models.FileField(blank=True, help_text='Archivo procesado (ej: imagen WebP comprimida)', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/mnt/volume_sfo3_02/multimedia/', location='C:\\Users\\User\\Documents\\NCS 2\\NSC-INTERNATIONAL\\multimedia'), upload_to=apps.media.models.multimedia_upload_path, verbose_name='Archivo Procesado'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Miniatura del archivo (generada automáticamente para videos)', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/mnt/volume_sfo3_02/multimedia/', location='C:\\Users\\User\\Documents\\NCS 2\\NSC-INTERNATIONAL\\multimedia'), upload_to=apps.media.models.multimedia_upload_path, verbose_name='Miniatura'),
        ),
    ]
